# Generated by Django 5.1.1 on 2024-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='def.png', null=True, upload_to='images/'),
        ),
    ]
